version: '3.0'
services:
    couchdb:
        image: 'couchdb:latest'
        ports:
            - '5984:5984'
    vault:
        image: 'vault:latest'
        ports:
            - '8200:8200'
        volumes:
            - './config:/vault/config'
        command: server
    vault-ui:
        image: 'djenriquez/vault-ui'
        ports:
            - '8000:8000'
        environment:
            - 'VAULT_URL_DEFAULT=http://vault:8200'
        
