version: '3.0'
services:
  consul:
    command: agent
    image: consul:latest
    volumes:
      - ./config/consul:/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  vault:
      image: 'vault:latest'
      ports:
          - '8200:8200'
      environment:
          - VAULT_ADDR=http://127.0.0.1:8200 # can remove this when publish to actual server
      volumes:
          - './config/vault:/vault/config'
      cap_add:
          - IPC_LOCK
      depends_on:
        - consul
      command: server
  vault-ui:
      image: 'djenriquez/vault-ui'
      ports:
          - '8000:8000'
      environment:
          - 'VAULT_URL_DEFAULT=http://vault:8200'
      depends_on:
        - vault
      
