dependencies:
  - name: consul
    version: ~1.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: vault
    version: ~0.3.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator