vault:
  image:
    tag: 0.9.3
  vault: 
    dev: false
    config:
      storage:
        consul:
          address: http://issa-consul:8500
          path: vault
          
consul:
  ImageTag: 1.0.6
  Replicas: 1
  ui:
    enabled: false
  uiService:
    enabled	: false